### ISSUE TITLE
Why is `index.js` obfuscated

### ISSUE THREAD

**Issue by m3hari** [morfien101/actions-authorized-user#2]
Just a simple question: In our team, we do a basic code review before using any open-source code; the completely obfuscated code makes it impossible to review this. 

Would you please add the source? I can help with setting up a build process if required. Thank you

**Comment by morfien101** [comment]
The index file is generated at build time and needs to be in the repo. It contains all the code that is used from node modules. This means I don't need to store the node modules in git or have you download them in the action.

You can see this in the build.sh file.

By cloning and building it yourself, you can verify this.

**Comment by m3hari** [comment]
I got it. It would have been nice if there had been a CI process that builds from source and publish to make it transparent.
